### PR TITLE
fix: fixed time for video

### LINKED ISSUE #94: Video rooms are completed too early
It seems that video rooms are completed to early as their time-to-live (5 minutes) is stored in seconds, but the completion timeout treats this as milliseconds, so rooms complete 1000x faster than they are meant to, meaning they can't actually be used since they're "deleted" almost instantly.

### PR DESCRIPTION
**Pull request by sahilsborkar**
Resolves #94 and #95

### CODE REVIEW

**Review by amishshah — CHANGES_REQUESTED** [review]
So this particular fix would break it when creating the room in Twilio - The twilio API takes the time in seconds, but setTimeout takes it in milliseconds

File: src/util/config/video.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// Room time limit is 5 minutes
+export const ROOM_TIME_LIMIT = 60 * 5;
+
+// Room time limit is 5 minutes, but converted milliseconds to seconds
```
Comment (amishshah) [inline src/util/config/video.ts]:
```suggestion
// Room time limit is 5 minutes, but converted seconds to milliseconds
```

File: src/util/config/video.ts [hunk 2]
```diff
@@ -0,0 +1,8 @@
...
+export const ROOM_TIME_LIMIT_CONV = 60 * 5 * 1000;
```
Comment (amishshah) [inline src/util/config/video.ts]:
```suggestion
export const ROOM_TIME_LIMIT_MS = 60 * 5 * 1000;
```

File: src/util/config/video.ts [hunk 3]
```diff
@@ -0,0 +1,8 @@
+// Room time limit is 5 minutes
+export const ROOM_TIME_LIMIT = 60 * 5;
```
Comment (amishshah) [inline src/util/config/video.ts]:
```suggestion
export const ROOM_TIME_LIMIT_SECS = 60 * 5;
```

**Review by amishshah — CHANGES_REQUESTED** [review]
I think it's best to make it explicit which variable is in seconds and which one is in milliseconds just so we don't accidentally mix up which one to use!

**Review by amishshah — APPROVED** [review]
